name: Deploy para AWS ECS

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Build, Push e Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login no AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Construir e enviar imagem Docker para o ECR
        run: |
          IMAGE_TAG=$(date +%s)
          docker buildx build --platform linux/amd64 -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Atualizar Task Definition
        run: |
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
