name: Deploy to AWS ECS

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Build, Push e Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=$(date +%s)
          docker buildx build --platform linux/amd64 -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update ECS Task Definition
        run: |
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
