name: API Deploy to AWS ECS

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set important variables
        run: |
          echo "REPO_NAME=chatmemoryapi" >> $GITHUB_ENV
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t $ECR_REGISTRY/$REPO_NAME:latest .
          docker push $ECR_REGISTRY/$REPO_NAME:latest

      - name: Update ECS Task Definition
        run: |
          aws ecs update-service --cluster meu-cluster \
            --service meu-servico-api \
            --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

